// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbgufcuqahnhjmfmmofj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiZ3VmY3VxYWhuaGptZm1tb2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3Mzg0MTAsImV4cCI6MjA3MzMxNDQxMH0.oCwx2X1-ZhNehesLR7og2izESyjgNEPhI56dDkA2O7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});